import comp from "D:/studySpace/kinghy-blog/src/.vuepress/.temp/pages/aitools/qoderUseFeel.html.vue"
const data = JSON.parse("{\"path\":\"/aitools/qoderUseFeel.html\",\"title\":\"Qoder 是什么\",\"lang\":\"zh-CN\",\"frontmatter\":{\"icon\":\"pen-to-square\",\"date\":\"2026-01-10T00:00:00.000Z\",\"cover\":\"/aitools/images/aitools1.png\",\"category\":[\"agent\",\"tools\"],\"tag\":[\"人工智能\",\"辅助编程\",\"工具\"],\"star\":10,\"description\":\"订阅了 Qoder 之后，我想通过这篇文章分享一些个人使用心得和感受。 Qoder 是什么 Qoder Qoder（/ˈkoʊdər/）是一款面向真实软件开发的 Agentic 编码平台。通过增强上下文工程与智能体无缝结合，全面理解你的代码库，并以系统化方式推进开发任务。 它提供代码智能生成、智能问答、多文件修改、编程智能体等能力，思考更深入、编码更高...\",\"head\":[[\"script\",{\"type\":\"application/ld+json\"},\"{\\\"@context\\\":\\\"https://schema.org\\\",\\\"@type\\\":\\\"Article\\\",\\\"headline\\\":\\\"Qoder 是什么\\\",\\\"image\\\":[\\\"https://kinghy949.github.io/kinghy-blog/aitools/images/aitools1.png\\\"],\\\"datePublished\\\":\\\"2026-01-10T00:00:00.000Z\\\",\\\"dateModified\\\":null,\\\"author\\\":[{\\\"@type\\\":\\\"Person\\\",\\\"name\\\":\\\"王海洋\\\",\\\"url\\\":\\\"https://kinghy949.github.io/kinghy-blog/\\\"}]}\"],[\"meta\",{\"property\":\"og:url\",\"content\":\"https://kinghy949.github.io/kinghy-blog/aitools/qoderUseFeel.html\"}],[\"meta\",{\"property\":\"og:site_name\",\"content\":\"王海洋的博客\"}],[\"meta\",{\"property\":\"og:title\",\"content\":\"Qoder 是什么\"}],[\"meta\",{\"property\":\"og:description\",\"content\":\"订阅了 Qoder 之后，我想通过这篇文章分享一些个人使用心得和感受。 Qoder 是什么 Qoder Qoder（/ˈkoʊdər/）是一款面向真实软件开发的 Agentic 编码平台。通过增强上下文工程与智能体无缝结合，全面理解你的代码库，并以系统化方式推进开发任务。 它提供代码智能生成、智能问答、多文件修改、编程智能体等能力，思考更深入、编码更高...\"}],[\"meta\",{\"property\":\"og:type\",\"content\":\"article\"}],[\"meta\",{\"property\":\"og:image\",\"content\":\"https://kinghy949.github.io/kinghy-blog/aitools/images/aitools1.png\"}],[\"meta\",{\"property\":\"og:locale\",\"content\":\"zh-CN\"}],[\"meta\",{\"name\":\"twitter:card\",\"content\":\"summary_large_image\"}],[\"meta\",{\"name\":\"twitter:image:src\",\"content\":\"https://kinghy949.github.io/kinghy-blog/aitools/images/aitools1.png\"}],[\"meta\",{\"name\":\"twitter:image:alt\",\"content\":\"Qoder 是什么\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"工具\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"辅助编程\"}],[\"meta\",{\"property\":\"article:tag\",\"content\":\"人工智能\"}],[\"meta\",{\"property\":\"article:published_time\",\"content\":\"2026-01-10T00:00:00.000Z\"}]]},\"readingTime\":{\"minutes\":4.07,\"words\":1222},\"filePathRelative\":\"aitools/qoderUseFeel.md\",\"excerpt\":\"<p>订阅了 Qoder 之后，我想通过这篇文章分享一些个人使用心得和感受。</p>\\n<h1>Qoder 是什么</h1>\\n<p><br>\\nQoder（/ˈkoʊdər/）是一款面向真实软件开发的 Agentic 编码平台。通过增强上下文工程与智能体无缝结合，全面理解你的代码库，并以系统化方式推进开发任务。</p>\\n<p>它提供代码智能生成、智能问答、多文件修改、编程智能体等能力，思考更深入、编码更高效、构建更出色，为开发者带来高效、流畅的编码体验。</p>\\n<p>其实就是是阿里对标Cursor而打造的一款编码产品</p>\\n<h2><a class=\\\"header-anchor\\\" href=\\\"#官网链接-https-qoder-ai\\\"><span>官网链接：</span></a><a href=\\\"https://qoder.com/referral?referral_code=bh1p27i5hGelnkvdrwCDjXzh0WaHI0FJ\\\" target=\\\"_blank\\\" rel=\\\"noopener noreferrer\\\">https://qoder.ai</a></h2>\",\"autoDesc\":true}")
export { comp, data }

if (import.meta.webpackHot) {
  import.meta.webpackHot.accept()
  if (__VUE_HMR_RUNTIME__.updatePageData) {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  }
}

if (import.meta.hot) {
  import.meta.hot.accept(({ data }) => {
    __VUE_HMR_RUNTIME__.updatePageData(data)
  })
}
